### PR TITLE
Fix indentation of display names when avatars are disabled

### PR DESCRIPTION
**Pull request by benjaminbhollon**

### CODE REVIEW

**Comment by cTheDragons** [comment]
Hi !

This is looking great. 

Do you have any time to look at the issues:
+ When you press info on the last message it does not auto scroll down.
+ Party chat the user information being hidden if skill is cast after the user
+ Party chat if the last message is system it is bold. 
+ Add the ability to choose the format of your date & time. 

No pressure only if you want. 

Thanks

**Comment by cTheDragons** [comment]
I'm also getting an error message when I think I open it for the first time from line 48,

: Uncaught TypeError: Cannot read property 'setAttribute' of null

**Comment by benjaminbhollon** [comment]
@cTheDragons That error is from the processNotifications() function. It looks like it is trying to apply the styling of an unread notification sometimes before the elements are there for it to apply the style to. I'll see what I can do, but I think it's mostly in which request takes longer to load...

I'd be happy to do some more work on this!

**Comment by cTheDragons** [comment]
Thank you!

The only other feature I was thinking of adding was the ability to hide system messages in chat. 

Is there a way we can do it dynamically? Like click something on the chat box to hide/show them?

The other items above would be more important though.

**Comment by benjaminbhollon** [comment]
It looks like there was an extra call to notifications that was unnecessary. I took it out, it shouldn't throw that error anymore.

**Comment by cTheDragons** [comment]
Another item to add. 

It has been requested that there be an option to choose whether the group list starts minimised when loading. (To avoid it being a distraction). I think if it is minimised too we should stop querying for notifications until it maximised and then query. 

Thanks

**Comment by benjaminbhollon** [comment]
I can definitely make it start minimized... I'll see if I can just disable checking for notifications while it's minimized.

**Comment by cTheDragons** [comment]
Thank you! Are you able to make it an option for those of us who are willing to start chatting away.

**Comment by benjaminbhollon** [comment]
I should be able to. Should it be collapsed by default?

**Comment by cTheDragons** [comment]
Lets make it so.

**Comment by cTheDragons** [comment]
Hi! did you see the [latest requirement from Staff](https://github.com/HabitRPG/habitica-chat-extension/pull/39) regarding calls?

We need to add to all header calls `x-client`  with a value of `chat-extension`  (alongside the x-api-user and x-api-key). Do you have time to do this? 

When also you like to finish your latest changes, as I will need to submit another round of testing.

Thanks again.

**Comment by benjaminbhollon** [comment]
@cTheDragons Sure. I'll work some on it now.

**Pull request merged**
